### ISSUE TITLE
Features / ToDo

### ISSUE THREAD

**Issue by Darguima** [Darguima/fake_blackboard#2]
### Main Tasks

- [] Extract Blackboard original icons, in `svg`, to use them in respective places.
- [] Recode bottom navigation tab, to use `svg` icons and `label text`, instead of a clip from a screenshot
- [] Recode `LoginPage` to ask the email in 3 differente parts (`prefix`, `student number`, `school domain` - see example below) to a more responsive interface, and replace where them are used (mainly in `ProfilePage`) 
`a` `105678`@`alunos.uuniversidade.pt`

### Add Content to secondary pages

- [] Code `LandingPage`
- [] Code `CoursesPage`
- [] Code `CalendarPage`
